version: "3.8"

services:
  hahnsimfront:
    build: ./hahn-sim-front
    container_name: hahnsimfront_c
    ports:
      - '3000:3000'
    environment:
      - API_BASE_URL=http://localhost:5103
      - CHOKIDAR_USEPOLLING=true 
    volumes:
      - ./hahn-sim-front/src:/app/src
      - ./hahn-sim-front/public:/app/public
      - /app/node_modules  
    stdin_open: true
    tty: true
    depends_on:
      - hahnsimback
    networks:
      - hahnsim-network

  
  hahnsimback:
    build: ./hahnsimback
    container_name: hahnsimback_c
    ports:
      - '5103:5103' #http
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:7133;http://+:5103
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=hahndb;User=sa;Password=Medlmz@2016;TrustServerCertificate=True;
    command: ["dotnet", "watch","run", -v, "--project" , "HahnSimBack.csproj", "--urls", "http://*:5103"]
    volumes:
      - ./hahnsimback:/app
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    networks:
      - hahnsim-network

  migration:
    build: ./hahnsimback
    command: ["dotnet", "ef", "database", "update"]
    depends_on:
      - sqlserver
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=hahndb;User=sa;Password=Medlmz@2016;TrustServerCertificate=True;
    networks:
      - hahnsim-network

  sqlserver:
      image: mcr.microsoft.com/mssql/server:2019-latest
      container_name: sqlserver_c
      ports: 
        - '1433:1433'
      environment:
        SA_PASSWORD: "Medlmz@2016"
        ACCEPT_EULA: "Y"
        MSSQL_PID: "Express"
      volumes:
        - sqlserver-data:/var/opt/mssql
      restart: unless-stopped
      networks:
        - hahnsim-network
      healthcheck:
        test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Medlmz@2016 -Q 'SELECT 1' || exit 1"]
        interval: 10s
        retries: 10
        start_period: 10s
        timeout: 3s
  

volumes:
  sqlserver-data:

networks:
  hahnsim-network:
    driver: bridge