FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app

EXPOSE 8083

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY ["HahnSimBack.csproj", "./"]
RUN dotnet restore "HahnSimBack.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "HahnSimBack.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "HahnSimBack.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "HahnSimBack.dll"]




